### ISSUE TITLE
Can't login with my dstar.su account

### ISSUE THREAD

**Issue by Eric-Sparks** [BrandMeister/Project-Halligan#15]
I created a dstar.su account and can login there but I keep getting the "Login failed due to an incorrect username and/or password!" error when I try to login to https://brandmeister.network/index.php?page=login.

**Comment by ON3YH** [comment]
Hey Eric,

we've had this issue before
Does your password contain any strange characters or symbols that are not used in the "daily life"?
Things like § or other strange symbols seem to corrupt the migration algorithm.
Please try to change your dstar.su password to something only containing a-z A-Z 0-9 or basic symbols.
If you keep having this issue, please don't hesitate to contact me.

Best 73'
Yentel - ON3YH

**Comment by Eric-Sparks** [comment]
Oh, I'm definitely using special characters.  I can't seem to find where to change my password on dstar.su.

**Comment by ON3YH** [comment]
This can be done on the PhpBB forum (the selfcare is coded as a phpbb extension).
Once you are logged in, visit this link:
https://www.dstar.su/forum/ucp.php?i=ucp_profile&mode=reg_details

**Comment by Eric-Sparks** [comment]
Great, I'm in.  Thanks!
