### ISSUE TITLE
Reflector connected - dashboard shows "Disconnect"

### ISSUE THREAD

**Issue by DL2MF** [BrandMeister/Project-Halligan#19]
Since the new version of Halligan is available I have noticed a difference between repeater status and dashboard.

When I query my repeater DB0CEL (262340) by 5000 voice announcement tells me "connected to 4011", but the interface shows me "disconnected", what my origin intention was, to remove the default link that was hardcoded in the old system.

Looks, like parts of the old reflector linking system is being remaining in use?

Also the way to get "disconnected" status working did change during the first week of new sysop panel. First 1-2 days it was possible to make a link to 4000 = disconnect, currently I have used "0" to get this status, because it's the only accepted input.

73 Meinhard, DL2MF

**Comment by zarya** [comment]
This problem is related to the master Sysops have been notified to go have a look.
