### ISSUE TITLE
Map confusing when setting repeater position for the first time

### ISSUE THREAD

**Issue by SteveCooling** [BrandMeister/Project-Halligan#20]
When the position of a repeater is at the default LAT 0 LON 0, the map is zoomed so far in that you cannot see land. Some users have reported to me "map not working" when seeing this.

I suggest zooming out to see the whole world when position is set to 0.000 , 0.000 to improve usability.

**Comment by zarya** [comment]
Internal issue created (issue 97)

**Comment by zarya** [comment]
Issue is fixed in the dev build hope to push the changes to production tomorrow

**Comment by zarya** [comment]
Issue is fixed
