### ISSUE TITLE
Profile picture not able to use

### ISSUE THREAD

**Issue by DB6KT** [BrandMeister/Project-Halligan#25]
it is not possibel to add an profile picture via --> user-->profile-->edit.
After upload and resize the picure, then I got an error message after saving the settings....
System: Acer Aspire 5380 with ArchLinux, cinnamon, Mozilla-Browser.....
73 de DB6KT - Thomas

**Comment by Yentel** [comment]
Hey there,
We are having some issues with the hoseline server, which also takes care
of the profile pictures.

We hope to resolve this as soon as possible :-)

Best 73'
Yentel - ON3YH

**Comment by DO5FOX** [comment]
# This is almost 3 months ago, even nothing's happened til now!
**Not picture able to upload it.
Not as URL and not from computer. 
No matter if jpg, png or gif. 
Not in firefox, not in chrome and not in the internet explorer...**
WHYYYYYYYYYYYYYYYYYYYYYYYYYYYY?

**Comment by DO5FOX** [comment]
**I want to have this profile picture in brandmeister.network:** http://www.bilder-upload.eu/upload/fae7c8-1503250711.jpg
## please make it anyhow.....
