### ISSUE TITLE
C4FM is being reported as DMR

### ISSUE THREAD

**Issue by kikosgc** [BrandMeister/Project-Halligan#26]
When in C4FM via a MMDVM repeater or Hotspot, we are reported,in the BrandMeister Dashboard, as DMR. Also, Source Call is also missing.
![Dashboard](https://user-images.githubusercontent.com/30269365/31908101-1df1eea2-b836-11e7-9b01-1bc93d6d1713.png)

> Its was a display error in the LH should be fixed now. (by PD0ZRY in Oct 21 '17)

**But unfortunately the problem persists.**

73

**Comment by zarya** [comment]
Seems to work fine here
![image](https://user-images.githubusercontent.com/387694/31915486-f499ad92-b84e-11e7-9d6d-50c175287c57.png)
the reason that the talkgroup has no name is that it does not have a name in our database the master sysop can request adding of names.

If it still does not work try clearing the browser caches.
