### ISSUE TITLE
selfcare blank

### ISSUE THREAD

**Issue by nackstein** [BrandMeister/Project-Halligan#28]
calling the url: https://brandmeister.network/?page=selfcare
I get the page with "SelfCare Settings" and a blank area under the heading.
I tested with firefox on linux (arch) and edge on windows 10, same result.
debugging the page I see on the network tab all green (200 status or 304 or 101)
on the console tab I get this error:
```
Done loading groups                                                                           groupInterface.js:13:9
Source map error: request failed with status 404
Resource URL: https://brandmeister.network/plugins/socket.io/socket.io-1.3.7.js
Source Map URL: socket.io.js.map

Source map error: request failed with status 404
Resource URL: https://brandmeister.network/plugins/daplie/bower_components/forge/dist/forge.min.js
Source Map URL: forge.min.js.map
```

Luigi

**Comment by zarya** [comment]
I am unable to reproduce your error with FF version 52.6.0 (64-bit) on debian testing

**Comment by nackstein** [comment]
My firefox is firefox quantum 58.0.2 (64-bit) on archlinux. I tested with a new incognito window, same error. I suspect some problem with my DMR account, my call is IU2GID.
On windows 10 with Microsoft Edge 41.16299.248.0 I tested with a inprivate windows and still get
a blank selfcare page, here on the console I see:
`
 HTML1300: Navigation occurred. brandmeister.network (1,1)
4 HTML1512: Unmatched end tag. brandmeister.network (439,144)
 CSS3121: The media query -ms-viewport has been deprecated.
 Done loading groups   groupInterface.js (13,9)
 `

I say I suspect an error in my DMR account because I'm also anable to send GPS coordinates from
my hytera AR685 and get a message "send failed" on all repeater I tested...

Luigi

**Comment by nackstein** [comment]
zarya: are you able to delete my account on the brandmeister server in order to let me recreate it?
I don't know if it matter but I recall that when I was waiting for my account activation I was already configuring my dashboard on dstar.su .... I don't really know where those registry are saved (I mean on which server/database) but maybe the concurrency of my action created some trouble....

**Comment by zarya** [comment]
The problem is solved. You where given a old ID that was disabled in our backends.

**Comment by nackstein** [comment]
yes! thank you very much!

**Comment by K7HJ** [comment]
I am unable to access the self help page after logging onto the Bandmaster Web page.  The page comes up saying "this page not working" and indicates HTTP ERROR 500 .  I am using Crome web browser.  Any assistance would be greatly appreciated
