### ISSUE TITLE
getting 404 on account settings

### ISSUE THREAD

**Issue by abutbul** [BrandMeister/Project-Halligan#33]
My callsign is 4z7dvx
I am trying to change it to 4X5PI (I have upgraded my license)
unable to perform any actions - getting 404 when trying to access my settings.

Thank you for your time devs!

**Comment by abutbul** [comment]
also unable to add any reflectors and now BM network banned me...

**Comment by abutbul** [comment]
my dmr id 4254039

please delete my user, I will recreate as needed. @zarya

**Comment by abutbul** [comment]
ok thanks :(

**Comment by cyanide-burnout** [comment]
Please use support.brandmeister.network
