### ISSUE TITLE
selfcare page does not open 

### ISSUE THREAD

**Issue by muratdekan** [BrandMeister/Project-Halligan#34]
The https 500 is showing an error. Page won't open

**Comment by p9a3** [comment]
I have this exact same issue, and have for weeks. My DMR ID is 1106153. Page won't load in any browser.

**Comment by zarya** [comment]
> I have this exact same issue, and have for weeks. My DMR ID is 1106153. Page won't load in any browser.

Yours is fixed.

**Comment by zarya** [comment]
@muratdekan i can not fix it for you if i don't know your callsign or dmr id

**Comment by p9a3** [comment]
Yes, thanks.

**Comment by sutty111** [comment]
Hi guys I'm having the same issue, cant get a hotspot to work and I'm guessing this has something to do with it, I am new to the network though. Call M7MKS I'd 2347766

**Comment by buhalo1** [comment]
Same issue, selfcare page not loading at all. BM ID 2503211

**Comment by zarya** [comment]
Both should be fixed, please if other people have this problem please create a issue at https://support.brandmeister.network/servicedesk/customer/portal/1/create/2
