### ISSUE TITLE
Expose the BrandMeister contact export functionality as an API

### ISSUE THREAD

**Issue by srinival4** [BrandMeister/Project-Halligan#45]
Please expose the BrandMeister contact export functionality as an API, with the same functionality as is currently available on the website i.e., given a comma-separated list of talkgroups as input to the API, the API returns the "contacts exports' output.

Background of why the feature is needed:

There are over 200K Radio IDs  on RadioID.net. The radioid list is available as a users.json file, which can be converted to CSV for updating a radio periodically (e.g: monthly). 
The Anytone UV878 Radios **only** holds 200K contacts.  So a trimmed contact list is needed to provide the most  useful information based on the talkgroups of interest.

Today, I am exporting the contacts who have last transmitted on a given list of talkgroups (as a .csv file from the BrandMeister contact export page)., and feeding it into a python program (that I wrote) to trim the radio ids based on the talkgroups of interest.

Request...

To automate this solution for the HAM community, will you please  expose the BrandMeister contact export functionality as an API, with the same functionality as is currently available on the website i.e., given a comma-seperated list of talkgroups as input to the API, the API returns the "contacts exports' output.

**Comment by criede** [comment]
Any news on this request? Would welcome that feature, too!
Thanks in advance
Christian DB9CR

**Comment by zarya** [comment]
It should be relative simple if you connect to the lastheard api (websocket) where this data is coming from in the dashboard see https://brandmeister.network/dist/js/bm/contactsExport.js

It has always been exposed just not documented.
